db:
  state_keeper_db_path: /home/oemerfurkan/Desktop/lambdaclass-2024/zksync/tantalus/chains/tantalus/db/main/state_keeper
  merkle_tree:
    path: /home/oemerfurkan/Desktop/lambdaclass-2024/zksync/tantalus/chains/tantalus/db/main/tree
    block_cache_size_mb: 32
    max_l1_batches_per_iter: 50
    memtable_capacity_mb: 512
    mode: FULL
    multi_get_chunk_size: 1000
    stalled_writes_timeout_sec: 50
  experimental:
    state_keeper_db_block_cache_capacity_mb: 128
eth:
  sender:
    proof_sending_mode: SKIP_EVERY_PROOF
    pubdata_sending_mode: BLOBS
    aggregate_tx_poll_period: 1
    aggregated_block_commit_deadline: 1
    aggregated_block_execute_deadline: 10
    aggregated_block_prove_deadline: 10
    aggregated_proof_sizes:
    - 1
    max_acceptable_priority_fee_in_gwei: 100000000000
    max_aggregated_blocks_to_commit: 1
    max_aggregated_blocks_to_execute: 10
    max_aggregated_tx_gas: 4000000
    max_eth_tx_data_size: 120000
    max_txs_in_flight: 30
    timestamp_criteria_max_allowed_lag: 30
    tx_poll_period: 1
    wait_confirmations: 1
  gas_adjuster:
    default_priority_fee_per_gas: 1000000000
    internal_l1_pricing_multiplier: 0.8
    internal_pubdata_pricing_multiplier: 1.0
    max_base_fee_samples: 10000
    num_samples_for_blob_base_fee_estimate: 10
    poll_period: 5
    pricing_formula_parameter_a: 1.5
    pricing_formula_parameter_b: 1.0005
  watcher:
    confirmations_for_eth_event: 0
    eth_node_poll_interval: 300
api:
  web3_json_rpc:
    http_port: 3050
    http_url: http://127.0.0.1:3050
    ws_port: 3051
    ws_url: ws://127.0.0.1:3051
    req_entities_limit: 10000
    account_pks:
    - 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    - 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
    - 0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
    - 0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6
    - 0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a
    - 0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba
    - 0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e
    - 0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356
    - 0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97
    - 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6
    - 0xf214f2b2cd398c806f84e317254e0f0b801d0643303237d97a22a48e01628897
    - 0x701b615bbdfb9de65240bc28bd21bbc0d996645a3dd57e7b12bc2bdf6f192c82
    - 0xa267530f49f8280200edf313ee7af6b827f2a8bce2897751d06a843f644967b1
    - 0x47c99abed3324a2707c28affff1267e45918ec8c3f20b8aa892e8b065d2942dd
    - 0xc526ee95bf44d8fc405a158bb884d9d1238d99f0612e9f33d006bb0789009aaa
    - 0x8166f546bab6da521a8369cab06c5d2b9e46670292d85c875ee9ec20e84ffb61
    - 0xea6c44ac03bff858b476bba40716402b03e41b8e97e276d1baec7c37d42484a0
    - 0x689af8efa8c651a91ad287602527f3af2fe9f6501a7ac4b061667b5a93e037fd
    - 0xde9be858da4a475276426320d5e9262ecfc3ba460bfac56360bfa6c4c28b4ee0
    - 0xdf57089febbacf7ba0bc227dafbffa9fc08a93fdc68e1e42411a14efcf23656e
    api_namespaces:
    - eth
    - net
    - web3
    - zks
    - pubsub
    - debug
    estimate_gas_acceptable_overestimation: 1000
    estimate_gas_scale_factor: 1.2
    filters_disabled: false
    filters_limit: 10000
    gas_price_scale_factor: 1.2
    max_nonce_ahead: 50
    max_response_body_size_overrides:
    - method: eth_getTransactionReceipt
    - method: zks_getProof
      size_mb: 64
    max_tx_size: 1000000
    pubsub_polling_interval: 200
    request_timeout: 10
    subscriptions_limit: 10000
  prometheus:
    listener_port: 3312
    pushgateway_url: http://127.0.0.1:9091
    push_interval_ms: 100
  healthcheck:
    port: 3071
    slow_time_limit_ms: null
    hard_time_limit_ms: null
  merkle_tree:
    port: 3072
base_token_adjuster:
  price_polling_interval_ms: 30000
basic_witness_input_producer:
  db_path: ./db/main/basic_witness_input_producer
  first_processed_batch: 0
  window_size: 3
circuit_breaker:
  http_req_max_retry_number: 5
  http_req_retry_interval_sec: 2
  replication_lag_limit_sec: 100
  sync_interval_ms: 30000
commitment_generator:
  max_parallelism: 10
contract_verifier:
  compilation_timeout: 30
  polling_interval: 1000
  port: 3070
  prometheus_port: 3314
  threads_per_server: 128
  url: http://127.0.0.1:3070
core_object_store:
  file_backed:
    file_backed_base_path: artifacts
  max_retries: 10
data_handler:
  http_port: 3320
  proof_generation_timeout_in_secs: 18000
  tee_support: true
house_keeper:
  fri_gpu_prover_archiver_archive_after_secs: 172800
  fri_gpu_prover_archiver_archiving_interval_ms: 86400000
  gpu_prover_queue_reporting_interval_ms: 10000
  l1_batch_metrics_reporting_interval_ms: 10000
  proof_compressor_job_retrying_interval_ms: 30000
  proof_compressor_stats_reporting_interval_ms: 10000
  prover_db_pool_size: 2
  prover_job_archiver_archive_after_secs: 172800
  prover_job_archiver_archiving_interval_ms: 1800000
  prover_job_retrying_interval_ms: 30000
  prover_stats_reporting_interval_ms: 5000
  witness_generator_job_retrying_interval_ms: 30000
  witness_generator_stats_reporting_interval_ms: 10000
  witness_job_moving_interval_ms: 40000
mempool:
  capacity: 10000000
  delay_interval: 100
  remove_stuck_txs: true
  stuck_tx_timeout: 86400
  sync_batch_size: 1000
  sync_interval_ms: 10
observability:
  log_directives: zksync_node_test_utils=info,zksync_state_keeper=info,zksync_reorg_detector=info,zksync_consistency_checker=info,zksync_metadata_calculator=info,zksync_node_sync=info,zksync_node_consensus=info,zksync_contract_verification_server=info,zksync_node_api_server=info,zksync_tee_verifier_input_producer=info,zksync_node_framework=info,zksync_block_reverter=info,zksync_commitment_generator=info,zksync_node_db_pruner=info,zksync_eth_sender=info,zksync_node_fee_model=info,zksync_node_genesis=info,zksync_house_keeper=info,zksync_proof_data_handler=info,zksync_shared_metrics=info,zksync_node_test_utils=info,zksync_vm_runner=info,zksync_consensus_bft=info,zksync_consensus_network=info,zksync_consensus_storage=info,zksync_core_leftovers=debug,zksync_server=debug,zksync_contract_verifier=debug,zksync_dal=info,zksync_db_connection=info,zksync_eth_client=info,zksync_eth_watch=debug,zksync_storage=info,zksync_db_manager=info,zksync_merkle_tree=info,zksync_state=debug,zksync_utils=debug,zksync_queued_job_processor=info,zksync_types=info,zksync_mempool=debug,loadnext=info,vm=info,zksync_object_store=info,zksync_external_node=info,zksync_witness_generator=info,zksync_prover_fri=info,zksync_witness_vector_generator=info,zksync_web3_decl=debug,zksync_health_check=debug,zksync_proof_fri_compressor=info,vise_exporter=error,snapshots_creator=debug,zksync_base_token_adjuster=debug
  log_format: plain
  opentelemetry:
    endpoint: unset
    level: debug
  sentry:
    environment: localhost
    error_interval: 10800
    panic_interval: 1800
    url: unset
operations_manager:
  delay_interval: 100
postgres:
  max_connections: 100
  statement_timeout_sec: 300
  test:
    prover_url: postgres://postgres:notsecurepassword@localhost:5433/prover_local_test
    server_url: postgres://postgres:notsecurepassword@localhost:5433/zksync_local_test
prometheus:
  listener_port: 3312
  push_interval_ms: 100
  pushgateway_url: http://127.0.0.1:9091
proof_compressor:
  compression_mode: 1
  generation_timeout_in_secs: 3600
  max_attempts: 5
  prometheus_listener_port: 3321
  prometheus_push_interval_ms: 100
  prometheus_pushgateway_url: http://127.0.0.1:9091
  universal_setup_download_url: https://storage.googleapis.com/matterlabs-setup-keys-us/setup-keys/setup_2^24.key
  universal_setup_path: keys/setup/setup_2^24.key
  verify_wrapper_proof: true
protective_reads_writer:
  db_path: ./db/main/protective_reads
  first_processed_batch: 0
  window_size: 3
prover:
  availability_check_interval_in_secs: 10000
  generation_timeout_in_secs: 600
  max_attempts: 10
  prometheus_port: 3315
  prover_object_store:
    file_backed:
      file_backed_base_path: artifacts
    max_retries: 10
  public_object_store:
    file_backed:
      file_backed_base_path: artifacts
    max_retries: 10
  queue_capacity: 10
  setup_data_path: vk_setup_data_generator_server_fri/data
  setup_load_mode: FROM_DISK
  shall_save_to_public_bucket: true
  specialized_group_id: 100
  witness_vector_receiver_port: 3316
  zone_read_url: http://metadata.google.internal/computeMetadata/v1/instance/zone
prover_gateway:
  api_poll_duration_secs: 1000
  api_url: http://127.0.0.1:3320
  prometheus_listener_port: 3314
  prometheus_push_interval_ms: 100
  prometheus_pushgateway_url: http://127.0.0.1:9091
prover_group:
  group_0:
  - aggregation_round: 4
    circuit_id: 1
  - aggregation_round: 2
    circuit_id: 2
  - aggregation_round: 0
    circuit_id: 255
  group_1:
  - aggregation_round: 0
    circuit_id: 1
  group_10:
  - aggregation_round: 0
    circuit_id: 10
  group_11:
  - aggregation_round: 1
    circuit_id: 7
  - aggregation_round: 1
    circuit_id: 8
  - aggregation_round: 1
    circuit_id: 10
  - aggregation_round: 1
    circuit_id: 11
  group_12:
  - aggregation_round: 1
    circuit_id: 4
  - aggregation_round: 1
    circuit_id: 5
  - aggregation_round: 1
    circuit_id: 6
  - aggregation_round: 1
    circuit_id: 9
  group_13:
  - aggregation_round: 0
    circuit_id: 14
  - aggregation_round: 0
    circuit_id: 15
  - aggregation_round: 0
    circuit_id: 255
  group_14:
  - aggregation_round: 1
    circuit_id: 16
  - aggregation_round: 1
    circuit_id: 17
  - aggregation_round: 1
    circuit_id: 18
  group_2:
  - aggregation_round: 0
    circuit_id: 2
  - aggregation_round: 0
    circuit_id: 4
  - aggregation_round: 0
    circuit_id: 6
  - aggregation_round: 0
    circuit_id: 9
  group_3:
  - aggregation_round: 0
    circuit_id: 3
  group_4:
  - aggregation_round: 0
    circuit_id: 11
  - aggregation_round: 0
    circuit_id: 12
  - aggregation_round: 0
    circuit_id: 13
  group_5:
  - aggregation_round: 0
    circuit_id: 5
  group_6:
  - aggregation_round: 1
    circuit_id: 3
  group_7:
  - aggregation_round: 0
    circuit_id: 7
  group_8:
  - aggregation_round: 0
    circuit_id: 8
  group_9:
  - aggregation_round: 1
    circuit_id: 12
  - aggregation_round: 1
    circuit_id: 13
  - aggregation_round: 1
    circuit_id: 14
  - aggregation_round: 1
    circuit_id: 15
pruning:
  chunk_size: 10
  data_retention_sec: 3600
  enabled: true
  removal_delay_sec: 60
snapshot_creator:
  concurrent_queries_count: 1
  object_store:
    file_backed:
      file_backed_base_path: artifacts
    max_retries: 10
  storage_logs_chunk_size: 2
snapshot_recovery:
  enabled: false
  experimental:
    drop_storage_key_preimages: true
    tree_recovery_parallel_persistence_buffer: 1
  postgres:
    max_concurrency: 10
  tree:
    chunk_size: 200000
state_keeper:
  batch_overhead_l1_gas: 800000
  block_commit_deadline_ms: 2500
  close_block_at_eth_params_percentage: 0.95
  close_block_at_gas_percentage: 0.95
  close_block_at_geometry_percentage: 0.95
  compute_overhead_part: 0
  fee_model_version: V1
  max_allowed_l2_tx_gas_limit: 4000000000
  max_circuits_per_batch: 24100
  max_gas_per_batch: 200000000
  max_pubdata_per_batch: 100000
  max_single_tx_gas: 6000000
  miniblock_commit_deadline_ms: 1000
  miniblock_max_payload_size: 1000000
  miniblock_seal_queue_capacity: 10
  minimal_l2_gas_price: 100000000
  protective_reads_persistence_enabled: true
  pubdata_overhead_part: 1
  reject_tx_at_eth_params_percentage: 0.95
  reject_tx_at_gas_percentage: 0.95
  reject_tx_at_geometry_percentage: 0.95
  save_call_traces: true
  transaction_slots: 250
  validation_computational_gas_limit: 300000
witness_generator:
  generation_timeout_in_secs: 900
  max_attempts: 10
  shall_save_to_public_bucket: true
witness_vector_generator:
  max_prover_reservation_duration_in_secs: 1000
  prometheus_listener_port: 3314
  prometheus_push_interval_ms: 100
  prometheus_pushgateway_url: http://127.0.0.1:9091
  prover_instance_poll_time_in_milli_secs: 250
  prover_instance_wait_timeout_in_secs: 200
  specialized_group_id: 100
